// ui/src/app/features/run-analysis/comparison-plot.component.ts
import {
  Component,
  effect,
  ElementRef,
  inject,
  input,
  OnChanges,
  OnDestroy,
  SimpleChanges,
  ViewChild,
} from '@angular/core';
import { FormsModule } from '@angular/forms';
import { SelectModule } from 'primeng/select';

import { ThemeService } from '../../core/services/theme.service';
import { RunAnalysisData, SelectOption } from './run-analysis.models';

@Component({
  selector: 'app-comparison-plot',
  standalone: true,
  imports: [FormsModule, SelectModule],
  templateUrl: './comparison-plot.component.html',
  styleUrl: './comparison-plot.component.css',
})
export class ComparisonPlotComponent implements OnChanges, OnDestroy {
  private readonly theme = inject(ThemeService);
  readonly data = input.required<RunAnalysisData>();
  readonly rows = input.required<Record<string, unknown>[]>();
  readonly maximized = input(false);
  private plotElement?: ElementRef<HTMLDivElement>;
  private resizeObserver?: ResizeObserver;
  parameterOptions: SelectOption[] = [];
  metricOptions: SelectOption[] = [];
  readonly scaleOptions: SelectOption[] = [
    { label: 'Linear', value: 'linear' },
    { label: 'Logarithmic', value: 'log' },
  ];
  xKey = '';
  yKey = '';
  xScale = 'linear';
  yScale = 'linear';
  plotMessage = '';

  @ViewChild('plot') set plotContainer(element: ElementRef<HTMLDivElement> | undefined) {
    this.resizeObserver?.disconnect();
    this.plotElement = element;
    if (element) {
      this.resizeObserver = new ResizeObserver(() => this.resize());
      this.resizeObserver.observe(element.nativeElement);
      window.setTimeout(() => this.draw());
    }
  }

  constructor() {
    effect(() => {
      this.theme.dark();
      window.setTimeout(() => this.draw());
    });
  }

  ngOnChanges(changes: SimpleChanges): void {
    if (changes['data']) {
      const columns = this.data().columns;
      this.parameterOptions = columns
        .filter((column) => column.kind === 'parameter')
        .map((column) => ({ label: column.label, value: column.key }));
      this.metricOptions = columns
        .filter((column) => column.kind === 'metric')
        .map((column) => ({ label: column.label, value: column.key }));
      this.xKey = this.parameterOptions[0]?.value || '';
      this.yKey = this.metricOptions[0]?.value || '';
    }
    window.setTimeout(() => (changes['maximized'] ? this.resize() : this.draw()), 100);
  }

  async draw(): Promise<void> {
    if (!this.plotElement || !this.xKey || !this.yKey) return;
    const analysis = this.data();
    const xColumn = analysis.columns.find((column) => column.key === this.xKey);
    const yColumn = analysis.columns.find((column) => column.key === this.yKey);
    const pairs = this.rows()
      .filter((row) =>
        [row[this.xKey], row[this.yKey]].every(
          (value) => value !== null && value !== undefined && value !== '',
        ),
      )
      .map((row) => ({
        x: Number(row[this.xKey]),
        y: Number(row[this.yKey]),
        series: String(row['__series'] || analysis.payload.software_name || 'Run'),
      }))
      .filter(
        (pair) =>
          Number.isFinite(pair.x) &&
          Number.isFinite(pair.y) &&
          (this.xScale !== 'log' || pair.x > 0) &&
          (this.yScale !== 'log' || pair.y > 0),
      );
    const groups = new Map<string, typeof pairs>();
    pairs.forEach((pair) => groups.set(pair.series, [...(groups.get(pair.series) || []), pair]));
    const traces = [...groups.entries()].map(([name, values]) => {
      const sorted = [...values].sort((a, b) => a.x - b.x);
      return {
        name,
        x: sorted.map((value) => value.x),
        y: sorted.map((value) => value.y),
        type: 'scatter',
        mode: 'lines+markers',
        hovertemplate: `${xColumn?.label}: %{x}<br>${yColumn?.label}: %{y}<extra>${name}</extra>`,
      };
    });
    this.plotMessage = `${pairs.length} plotted from ${this.rows().length} filtered observations`;
    const Plotly = (await import('plotly.js-dist-min')).default;
    const colors = this.theme.colors();
    Plotly.react(
      this.plotElement.nativeElement,
      traces,
      {
        margin: { l: 75, r: 24, t: 25, b: 70 },
        showlegend: traces.length > 1,
        hovermode: 'closest',
        paper_bgcolor: colors.surface,
        plot_bgcolor: colors.plot,
        font: { color: colors.text, family: 'IBM Plex, Arial, sans-serif' },
        colorway: ['#046cb4', '#e6005f', '#f9b200', '#792182', '#00763c', '#ee7202'],
        xaxis: {
          title: { text: xColumn?.label },
          type: this.xScale,
          automargin: true,
          gridcolor: colors.line,
          zerolinecolor: colors.line,
        },
        yaxis: {
          title: { text: yColumn?.label, standoff: 14 },
          type: this.yScale,
          automargin: true,
          gridcolor: colors.line,
          zerolinecolor: colors.line,
        },
      },
      {
        responsive: true,
        displaylogo: false,
        scrollZoom: true,
        modeBarButtonsToRemove: ['lasso2d', 'select2d'],
      },
    );
  }

  private async resize(): Promise<void> {
    const element = this.plotElement?.nativeElement as
      (HTMLDivElement & { _fullLayout?: unknown }) | undefined;
    if (!element?._fullLayout) return;
    const Plotly = (await import('plotly.js-dist-min')).default;
    window.requestAnimationFrame(() => Plotly.Plots.resize(element));
  }

  ngOnDestroy(): void {
    this.resizeObserver?.disconnect();
  }
}

<section class="plot-panel" [class.maximized]="maximized()">
  <div class="axis-groups">
    <fieldset>
      <legend>X axis</legend>
      <label>
        Parameter
        <p-select
          [options]="parameterOptions"
          [(ngModel)]="xKey"
          optionLabel="label"
          optionValue="value"
          (onChange)="draw()"
        />
      </label>
      <label>
        Scale
        <p-select
          [options]="scaleOptions"
          [(ngModel)]="xScale"
          optionLabel="label"
          optionValue="value"
          (onChange)="draw()"
        />
      </label>
    </fieldset>

    <fieldset>
      <legend>Y axis</legend>
      <label>
        Metric
        <p-select
          [options]="metricOptions"
          [(ngModel)]="yKey"
          optionLabel="label"
          optionValue="value"
          (onChange)="draw()"
        />
      </label>
      <label>
        Scale
        <p-select
          [options]="scaleOptions"
          [(ngModel)]="yScale"
          optionLabel="label"
          optionValue="value"
          (onChange)="draw()"
        />
      </label>
    </fieldset>
  </div>

  <p class="plot-message">{{ plotMessage }}</p>
  <div #plot class="plot"></div>
</section>

// ui/src/components/ComparisonPlot.vue
<script setup lang="ts">
import { computed, nextTick, onBeforeUnmount, onMounted, ref, watch } from 'vue';
import Select from 'primevue/select';
import { colors } from '../lib/theme';
import type { AnalysisRow, RunAnalysisData } from '../lib/analysis';

const props = defineProps<{ data: RunAnalysisData; rows: AnalysisRow[]; maximized: boolean }>();
const plot = ref<HTMLDivElement | null>(null);
const xKey = ref('');
const yKey = ref('');
const xScale = ref<'linear' | 'log'>('linear');
const yScale = ref<'linear' | 'log'>('linear');
const plotMessage = ref('');
const parameterOptions = computed(() =>
  props.data.columns
    .filter((column) => column.kind === 'parameter')
    .map((column) => ({ label: column.label, value: column.key })),
);
const metricOptions = computed(() =>
  props.data.columns
    .filter((column) => column.kind === 'metric')
    .map((column) => ({ label: column.label, value: column.key })),
);
const scaleOptions = [
  { label: 'Linear', value: 'linear' },
  { label: 'Logarithmic', value: 'log' },
];
let resizeObserver: ResizeObserver | undefined;

watch(
  () => props.data,
  () => {
    xKey.value = parameterOptions.value[0]?.value || '';
    yKey.value = metricOptions.value[0]?.value || '';
  },
  { immediate: true },
);
watch(
  [() => props.rows, () => props.maximized, colors, xKey, yKey, xScale, yScale],
  () => void draw(),
  { deep: true },
);

async function draw(): Promise<void> {
  await nextTick();
  if (!plot.value || !xKey.value || !yKey.value) return;
  const xColumn = props.data.columns.find((column) => column.key === xKey.value);
  const yColumn = props.data.columns.find((column) => column.key === yKey.value);
  const pairs = props.rows
    .filter((row) =>
      [row[xKey.value], row[yKey.value]].every(
        (value) => value !== null && value !== undefined && value !== '',
      ),
    )
    .map((row) => ({
      x: Number(row[xKey.value]),
      y: Number(row[yKey.value]),
      series: String(row['__series'] || props.data.payload.software_name || 'Run'),
    }))
    .filter(
      (pair) =>
        Number.isFinite(pair.x) &&
        Number.isFinite(pair.y) &&
        (xScale.value !== 'log' || pair.x > 0) &&
        (yScale.value !== 'log' || pair.y > 0),
    );
  const groups = new Map<string, typeof pairs>();
  pairs.forEach((pair) => groups.set(pair.series, [...(groups.get(pair.series) || []), pair]));
  const traces = [...groups.entries()].map(([name, values]) => {
    const sorted = [...values].sort((a, b) => a.x - b.x);
    return {
      name,
      x: sorted.map((value) => value.x),
      y: sorted.map((value) => value.y),
      type: 'scatter' as const,
      mode: 'lines+markers' as const,
      hovertemplate: `${xColumn?.label}: %{x}<br>${yColumn?.label}: %{y}<extra>${name}</extra>`,
    };
  });
  plotMessage.value = `${pairs.length} plotted from ${props.rows.length} filtered observations`;
  const Plotly = (await import('plotly.js-dist-min')).default;
  await Plotly.react(
    plot.value,
    traces,
    {
      margin: { l: 75, r: 24, t: 25, b: 70 },
      showlegend: traces.length > 1,
      hovermode: 'closest',
      paper_bgcolor: colors.value.surface,
      plot_bgcolor: colors.value.plot,
      font: { color: colors.value.text, family: 'IBM Plex, Arial, sans-serif' },
      colorway: ['#046cb4', '#e6005f', '#f9b200', '#792182', '#00763c', '#ee7202'],
      xaxis: {
        title: { text: xColumn?.label },
        type: xScale.value,
        automargin: true,
        gridcolor: colors.value.line,
        zerolinecolor: colors.value.line,
      },
      yaxis: {
        title: { text: yColumn?.label, standoff: 14 },
        type: yScale.value,
        automargin: true,
        gridcolor: colors.value.line,
        zerolinecolor: colors.value.line,
      },
    },
    {
      responsive: true,
      displaylogo: false,
      scrollZoom: true,
      modeBarButtonsToRemove: ['lasso2d', 'select2d'],
    },
  );
}

onMounted(() => {
  if (plot.value) {
    resizeObserver = new ResizeObserver(() => {
      if (plot.value)
        void import('plotly.js-dist-min').then((module) =>
          module.default.Plots.resize(plot.value!),
        );
    });
    resizeObserver.observe(plot.value);
  }
  void draw();
});
onBeforeUnmount(() => {
  resizeObserver?.disconnect();
  if (plot.value)
    void import('plotly.js-dist-min').then((module) => module.default.purge(plot.value!));
});
</script>

<template>
  <section class="plot-panel" :class="{ maximized }">
    <div class="axis-groups">
      <fieldset>
        <legend>X axis</legend>
        <label
          >Parameter<Select
            v-model="xKey"
            :options="parameterOptions"
            option-label="label"
            option-value="value" /></label
        ><label
          >Scale<Select
            v-model="xScale"
            :options="scaleOptions"
            option-label="label"
            option-value="value"
        /></label>
      </fieldset>
      <fieldset>
        <legend>Y axis</legend>
        <label
          >Metric<Select
            v-model="yKey"
            :options="metricOptions"
            option-label="label"
            option-value="value" /></label
        ><label
          >Scale<Select
            v-model="yScale"
            :options="scaleOptions"
            option-label="label"
            option-value="value"
        /></label>
      </fieldset>
    </div>
    <p class="plot-message">{{ plotMessage }}</p>
    <div ref="plot" class="plot"></div>
  </section>
</template>
